### ISSUE TITLE
Implement quality assurance

### ISSUE THREAD

**Issue by tgvdinesh** [tgvdinesh/mind-sport-intellij-plugin#5]
# Task
- [ ] Implement Unit Testing
- [ ] Add Code coverage
- [ ] Put bade in README.md
